name: model_helper
description: Helper code generator for models.

publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:

  build: ^2.1.1
  source_gen: ^1.2.0

  model_annotations:
    path: model_annotations

dev_dependencies:

  build_runner: ^2.1.5

  test: ^1.0.0
